server: 
  port : 8086

spring:
  application:
    name: CO-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
  config:
    import: optional:configserver:http://localhost:2222
    
  datasource:
    userName: root
    password: Password1
    url: jdbc:mysql://localhost:3306/his?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true

  mail:
    host: smtp.gmail.com
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: 
accessKey : 
secret : 
bucketName : 
region : 
 
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'

